import xml.etree.ElementTree as ET
from jinja2 import Template
from datetime import datetime
import smtplib
from email.message import EmailMessage

# from scripts.generate_report import OUTPUT_HTML
# Result file generated by TCShell
RESULT_XML = r"C:\ToscaReports\result.xml"
OUTPUT_HTML = r"C:\ToscaReports\Tosca_Report.html"

# Parse XML
tree = ET.parse(RESULT_XML)
root = tree.getroot()

testcases = []

for tc in root.findall(".//TestCase"):
    testcases.append({
        "name": tc.get("name"),
        "result": tc.get("result"),
        "duration": tc.get("duration")
    })

passed = sum(1 for t in testcases if t["result"] == "Passed")
failed = sum(1 for t in testcases if t["result"] == "Failed")

# HTML Template
html_template = """
<html>
<head>
<title>Tosca Custom Report</title>
<style>
body {font-family: Arial;}
.pass {color: green;}
.fail {color: red;}
table {border-collapse: collapse; width: 80%;}
th, td {border:1px solid #ccc; padding:8px;}
</style>
</head>

<body>

<h2>Tosca Automation Report</h2>
<p>Generated: {{date}}</p>

<h3>Summary</h3>
<ul>
<li>Passed: {{passed}}</li>
<li>Failed: {{failed}}</li>
<li>Total: {{total}}</li>
</ul>

<table>
<tr>
<th>Test Case</th>
<th>Result</th>
<th>Duration</th>
</tr>

{% for tc in testcases %}
<tr>
<td>{{tc.name}}</td>
<td class="{{ 'pass' if tc.result=='Passed' else 'fail' }}">
{{tc.result}}
</td>
<td>{{tc.duration}} sec</td>
</tr>
{% endfor %}

</table>

</body>
</html>
"""

template = Template(html_template)

html_output = template.render(
    testcases=testcases,
    passed=passed,
    failed=failed,
    total=len(testcases),
    date=datetime.now()
)

with open(OUTPUT_HTML, "w") as f:
    f.write(html_output)

print("✅ Custom HTML report generated!")

# Email Report

msg = EmailMessage()
msg['Subject'] = 'Tosca Automation Report'
msg['From'] = 'niteshbadge1505@gmail.com'
msg['To'] = 'niteshtestautomation@gmail.com'

msg.set_content("Attached Tosca execution report.")

with open(OUTPUT_HTML, 'rb') as f:
    msg.add_attachment(f.read(),
                       maintype='text',
                       subtype='html',
                       filename='Tosca_Report.html')

with smtplib.SMTP('smtp.gmail.com', 587) as s:
    s.starttls()
    s.login('your_email@gmail.com', '')
    s.send_message(msg)

# with smtplib.SMTP('smtp.server.com', 587) as s:
#     s.starttls()
#     s.login('user','password')
#     s.send_message(msg)